### ISSUE TITLE
Re-Run after hitting an error

### ISSUE THREAD

**Issue by fmassa** [torch/trepl#16]
I experienced the same problem as Siavash Sakhavi in https://groups.google.com/forum/embed/?place=forum%2Ftorch7#!topic/torch7/vUp2dTkic54 while using th.
I haven't explored it further in detail, but when there is a bug in a .lua code, th runs it twice before outputting the error.

Here is a code snippet that reproduces this behaviour

```
require 'torch'

a = torch.Tensor({1,2,3})
print('here')
b = torch.FloatTensor({2,3,4})

c = a+b
```
The output after executing this file with dofile in th is
```
th> dofile 'tst.lua'
here	
here	
bad argument #2 to '?' (number expected, got userdata)
stack traceback:
	[C]: at 0x7f1c1963f900
	[C]: in function '__add'
	tst.lua:7: in main chunk
	[C]: in function 'dofile'
	[string "dofile 'tst.lua'"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/francisco/torch/install/share/lua/5.1/trepl/init.lua:588: in function 'repl'
	...isco/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406170	

```

Note that the `here` is displayed twice.

**Comment by soumith** [comment]
Looks like Line 588 has to be deleted. wdyt @clementfarabet 
https://github.com/torch/trepl/blob/master/init.lua#L588

Line 581 already ran the code, and 588 is trying to run the code again.

**Comment by clementfarabet** [comment]
Should be fixed here:
https://github.com/torch/trepl/commit/6c14b137a77488384b37f4e423b219cd48dbf4a3

**Comment by ssakhavi** [comment]
@soumith and @clementfarabet , I am still having the same problem. Even when I Ctrl+C, executes again.

**Comment by soumith** [comment]
@ssakhavi did you reinstall trepl using  "luarocks install trepl"?

**Comment by soumith** [comment]
I can verify that it works fine on my end.

**Comment by ssakhavi** [comment]
OK. I'll look into the problem again .

Thanks

**Comment by ssakhavi** [comment]
I re-installed the torch-distro. It got fixed.
